import "./globals.css";
import Navbar from "./components/NavBar";
import { Geist, Geist_Mono } from "next/font/google";
import type { Metadata } from "next";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Vaihtoaktivaattori", // TODO: change title when it's finalized
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fi">
      <body className={` antialiased`}>
        <Navbar />
        <main className="mx-auto max-w-6xl">{children}</main>
      </body>
    </html>
  );
}
