import "./globals.css";
import Navbar from "../components/NavBar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Vaihtoaktivaattori", // TODO: change title when it's finalized
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fi">
      <body className={` antialiased`}>
        <Navbar />
        <main className="mx-auto max-w-full mb-10">{children}</main>
      </body>
    </html>
  );
}
